from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name_fa', models.CharField(default='امداد خودرو مشهد', max_length=120)),
                ('brand_name_en', models.CharField(default='Mashhad Roadside Assistance', max_length=120)),
                ('phone', models.CharField(default='09120000000', max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('tagline_fa', models.CharField(default='امداد خودرو مشهد، ۲۴ ساعته کنار شما', max_length=255)),
                ('tagline_en', models.CharField(default='24/7 roadside assistance across Mashhad', max_length=255)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('city_fa', models.CharField(default='مشهد', max_length=80)),
                ('city_en', models.CharField(default='Mashhad', max_length=80)),
                ('working_hours', models.CharField(default='24/7', max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title_fa', models.CharField(default='امداد خودرو مشهد | امداد خودرو ۲۴ ساعته', max_length=70)),
                ('meta_title_en', models.CharField(default='Mashhad Roadside Assistance | 24/7', max_length=70)),
                ('meta_description_fa', models.CharField(blank=True, max_length=170)),
                ('meta_description_en', models.CharField(blank=True, max_length=170)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={'verbose_name': 'تنظیمات SEO', 'verbose_name_plural': 'تنظیمات SEO'},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_fa', models.TextField()),
                ('description_en', models.TextField()),
                ('icon', models.CharField(default='wrench', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ], options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('models_fa', models.TextField(blank=True)),
                ('models_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ], options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title_fa', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('excerpt_fa', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('content_fa', models.TextField()),
                ('content_en', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70)),
                ('meta_title_en', models.CharField(blank=True, max_length=70)),
                ('meta_description_fa', models.CharField(blank=True, max_length=170)),
                ('meta_description_en', models.CharField(blank=True, max_length=170)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ], options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_fa', models.CharField(max_length=300)),
                ('question_en', models.CharField(max_length=300)),
                ('answer_fa', models.TextField()),
                ('answer_en', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ], options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('text_fa', models.TextField()),
                ('text_en', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ], options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_fa', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ], options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('vehicle', models.CharField(blank=True, max_length=120)),
                ('problem', models.CharField(choices=[('towing', 'یدک‌کش / خودروبر'), ('battery', 'باتری'), ('flat_tire', 'پنچری'), ('mechanic', 'مکانیک سیار'), ('fuel', 'سوخت‌رسانی'), ('lockout', 'قفل / کلید'), ('electrical', 'برق خودرو'), ('accident', 'تصادف'), ('other', 'سایر')], default='other', max_length=30)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=30)),
            ], options={'ordering': ['-created_at']},
        ),
    ]
